version: "3.9"

services:
  app:
    env_file: .env
    restart: always
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - .:/app

    depends_on:
      - db

    environment:
      - PGHOST=db

  parser:
    env_file: .env
    restart: always
    build: ./parser
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PGHOST=db

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
